### PR TITLE
Added new properties

### PR DESCRIPTION
**Pull request by edger-asiimwe**
**Added attributes for the following classes;**
_1. Document
2. Animation
3. PhotoSize_

### CODE REVIEW

**Review by ht-thomas — CHANGES_REQUESTED** [review]
hey @edger-asiimwe ,thanks for the PR, but we're now adding properties to classes following gh-24 way of doing it.

**Review by moses-kisakye — COMMENTED** [review]
I think this needs an **appreciation!!**

**Comment by edger-asiimwe** [comment]
@ht-thomas Kindly review the new commit

**Comment by ht-thomas** [comment]
@edger-asiimwe thanks for making the changes and also adding documentation. this is great work.

**Pull request merged**
