### PR TITLE
Add idea for autobot logo

### PR DESCRIPTION
**Pull request by asbenjamin**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] I have included in this PR's description the statement `closes #xx` or `fixes #xx` where #xx is the number of the issue being addressed.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
The current logo is not representative of Autobot, is a transformers logo and there is a possibility that it may be copywritten.

* **What is the new behavior (if this is a feature change)?**
The new logo will have features of Autobot as nodes from the gear, such as the bot feature, the database feature

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by ht-thomas** [comment]
Thanks @asbenjamin for this. 
@kallyas @ushergodwin @ushergodwin @HassanBahati @mosespace what do you guys think

**Comment by HassanBahati** [comment]
> Thanks @asbenjamin for this. @kallyas @ushergodwin @ushergodwin @HassanBahati @mosespace what do you guys think. Personally I feel the colors are a bit unrepresentative. The reason we're using orange is because it's osca's theme color. Also I feel the middle stuff are a bit too complex, something as simple as just a single gear, or two to three of them in proportional sizes would be enough. I'd also suggest the font to be proportional, this looks a bit flattened. Thanks again for the PR, that's my review

thanks @asbenjamin , i second you about copyright issues...I seek to understand what inspiration we are having for the new logo. What message could be under the hood of our new logo?

**Comment by asbenjamin** [comment]
> > Thanks @asbenjamin for this. @kallyas @ushergodwin @ushergodwin @HassanBahati @mosespace what do you guys think. Personally I feel the colors are a bit unrepresentative. The reason we're using orange is because it's osca's theme color. Also I feel the middle stuff are a bit too complex, something as simple as just a single gear, or two to three of them in proportional sizes would be enough. I'd also suggest the font to be proportional, this looks a bit flattened. Thanks again for the PR, that's my review
> 
> thanks @asbenjamin , i second you about copyright issues...I seek to understand what inspiration we are having for the new logo. What message could be under the hood of our new logo?

So, on the color @ht-thomas, I am using orange and black, black is the secondary color. Orange the primary or main color.

@HassanBahati, the inspiration behind my design was that autobot will be for building multiple platforms, and just wanted to play with the nodes, as you can see one has a robot and the other has a database.

**Comment by ht-thomas** [comment]
For the sake of managing complexity, I thought it best to make autobot fulfill it's original goal, then we shall build other projects for automation and web called autoevents and autoweb respectively. So the moving gears can be for the autoevents framework, autobot can have a bot head if so, and autoweb will have it's own logo if so.

**Comment by kallyas** [comment]
Any final thoughts and conclusions on this? @asbenjamin @ht-thomas @HassanBahati @ushergodwin

**Comment by asbenjamin** [comment]
> For the sake of managing complexity, I thought it best to make autobot fulfill it's original goal, then we shall build other projects for automation and web called autoevents and autoweb respectively. So the moving gears can be for the autoevents framework, autobot can have a bot head if so, and autoweb will have it's own logo if so.

@ht-thomas so that means 3 different logos, okay. Let me work on the events and bot one. Which one comes first, autobot?

If autobot, I'll try to modify the current design and update this PR, then do the events one after

**Comment by ht-thomas** [comment]
@asbenjamin autobot comes first. The rest are still far from coding them yet

**Comment by mosespace** [comment]
> @asbenjamin 

  Try modifying the current design and let's really aim at that sofa. The-other will come after there coding process.

> @ht-thomas 

!I suggest the logo to favor both the dark and light mode.

**Pull request closed without merging**
