### PR TITLE
gh-99 added message methods

### PR DESCRIPTION
**Pull request by ushergodwin**
### gh-99 added message methods
@ht-thomas confirm if am on the right track.

### CODE REVIEW

**Comment by ht-thomas** [comment]
@ushergodwin yeah, this is it.

**Comment by ht-thomas** [comment]
@ushergodwin I think the changes you made to the `__init__.py` imports are causing the tests to fail

**Comment by ushergodwin** [comment]
> @ushergodwin what was making the tests fail?

I moved the `ForceReply` object from `forcereply.py` to `replykeyboard...py` since it looked isolated. I then changed the import in `__init__.py` to reflect the new object path. 

The tests failed. So my assumption was that since the test validates the objects again the ones in the Telegram API, maybe changing its location could have made themfail. 
So I put it back in its original file and, reverted the import to how it was before I changed it.

But still, the tests are failing, they stop on scanning the object.

**Comment by ht-thomas** [comment]
@ushergodwin The forcereply.py module was filled in by @kallyas in the issue I had here #116 .
So I think we should stick with the previous API because the parser also relies on its existence

**Comment by ushergodwin** [comment]
Okay, let me revert

**Pull request closed without merging**
