### PR TITLE
ch: partially add api methods

### PR DESCRIPTION
**Pull request by kallyas**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] I have included in this PR's description the statement `closes #xx` or `fixes #xx` where #xx is the number of the issue being addressed.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by kallyas** [comment]
@ht-thomas some of the methods are really confusing

**Comment by ht-thomas** [comment]
@kallyas like which ones?

**Comment by kallyas** [comment]
Where It returns a boolean

**Comment by ht-thomas** [comment]
> Where It returns a boolean

@kallyas which method is that specifically?

**Pull request merged**
