### PR TITLE
fix: circular import errors

### PR DESCRIPTION
**Pull request by kallyas**
This PR Fixes circular import errors

### CODE REVIEW

**Comment by kallyas** [comment]
@ht-thomas @ushergodwin How are we going to handle this? Caused by type hints in `Message` Object ?

image

**Comment by edger-asiimwe** [comment]
@kallyas the tests didn't pass

**Comment by kallyas** [comment]
> @kallyas the tests didn't pass

Yes, Because of the `Message` Object who's some of the properties are `Message` objects thus causing circular import error after adding type hints

**Comment by ht-thomas** [comment]
The best solution now is to separate types from objects. Let me try working out to work out a feasible way to do it

**Comment by kallyas** [comment]
After using `TYPE_CHECKING`, problem was solved, however another import problem has come up

```bash
from games.objects import Game
ModuleNotFoundError: No module named 'games'
```

**Comment by ht-thomas** [comment]
@kallyas what I know is that there are many errors in the system that are yet to be revealed. Whatever needs to be refactored shall have to be refactored in order to get rid of the bugs.

**Comment by ht-thomas** [comment]
I think we should focus on fixing import errors as of now. I see the checks have captured a new error. We can merge this pr and then work on the error and fix any more hidden errors till we're done. so you said that this PR fixes some circular import errors, let's merge it and work on the one I'm seeing in InlineQuery

**Comment by ht-thomas** [comment]
@kallyas I've just looked through the image clearly now. There's not point in import a file module that contains the object that is being declared in that file. That will create needless circular import since the object is already in the file that you're trying to import.
In this case you can just use the object as it is cause it's already there

**Comment by kallyas** [comment]
> 

The one for `User` ?

**Pull request merged**
