### PR TITLE
added properties to the voice object

### PR DESCRIPTION
**Pull request by nklubega**
This addresses #24 by adding properties to voice.py

### CODE REVIEW

**Comment by kallyas** [comment]
@nklubega Your PR has conflicts,

**Comment by ht-thomas** [comment]
@nklubega you PR is introducing merge conficts to the codebase. I would suggest to first update your fork by pulling the changes you don't have and then wroking your PR around those changes

**Comment by nklubega** [comment]
> @nklubega you PR is introducing merge conficts to the codebase. I would suggest to first update your fork by pulling the changes you don't have and then wroking your PR around those changes

Sorry I hadn't synced my forked repo with the original. I've just noticed changes were already made to voice.py. Should I just close the PR in this case?

**Comment by kallyas** [comment]
> > @nklubega you PR is introducing merge conficts to the codebase. I would suggest to first update your fork by pulling the changes you don't have and then wroking your PR around those changes
> 
> Sorry I hadn't synced my forked repo with the original. I've just noticed changes were already made to voice.py. Should I just close the PR in this case?

Yes, you can close this PR

**Comment by ht-thomas** [comment]
@nklubega I think you should close the PR because all objects were worked on. I think I forgot to update the checks on the issue that you referenced. I think it's time to close that issue because the tests show that all objects are worked on

**Pull request closed without merging**
