### PR TITLE
[docs] Updated #114

### LINKED ISSUE #105: add contributing guide
There is no clear path or road map for new contributors to follow as they onboard creating necessity for a guide through setting up to raising their first contribution.

The guide should include not limited to;

- A description about the project 
- Steps to follow when setting up
- Finding what to work on
- Instructions on making a code change
- Documenting
-

### LINKED ISSUE #130: [docs] inconsistency when toggling between dark and light mode
When you toggle between light mode, system mode and dark mode, there are inconsistencies as the page content changes which shouldn't be happening.

With light mode and system mode, we seem to have same content, but when toggled to dark mode, the page is different.

 The content should be the same across various modes.

Screenshot from 2022-11-24 07-31-20

Screenshot from 2022-11-24 07-26-48

### PR DESCRIPTION
**Pull request by mosespace**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] I have included in this PR's description the statement `closes #xx` or `fixes #xx` where #xx is the number of the issue being addressed.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 This pr adds both new features, updates and as well as fixes bugs!

* **What is the current behavior?** (You can also link to an open issue here)
 At he current state: there was a bug on the dark mode and light mode which was fixed!

* **What is the new behavior (if this is a feature change)?**
 Now the program is able to run in all the three light stages without making any changes to the styling!

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
 No breaking change is required on this pull request!

* **Other information**
This pr closes #130
This pr closes #105

### CODE REVIEW

**Comment by mosespace** [comment]
I had to delete the whole branch and redo stuff. unfortunately i had many branches created that were disturbing me to figure out!!!

@HassanBahati am calling in for a review.
Thank you

**Comment by mosespace** [comment]
> * **Please check if the PR fulfills these requirements**
> 
> * [x]  Tests for the changes have been added (for bug fixes/features)
> * [x]  Docs have been added / updated (for bug fixes / features)
> * [x]  I have included in this PR's description the statement `closes #xx` or `fixes #xx` where #xx is the number of the issue being addressed.
> 
> * **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
> * **What is the current behavior?** (You can also link to an open issue here)
> * **What is the new behavior (if this is a feature change)?**
> * **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
> * **Other information**:

Thank you for the pull request request!! its dope :+1: :smile:

**Comment by mosespace** [comment]
I'have also resolved the bug on issue GH-130 you can check it out [here](https://github.com/OSCA-Kampala-Chapter/autobot/pull/136/commits/851fd9119e1f96cb86b46573f57c4487d7c6bda5)

**Comment by mosespace** [comment]
I've also resolved the issue GH-105 you can check it out [here](https://github.com/OSCA-Kampala-Chapter/autobot/pull/136/commits/ddbba4df189afb2376eb3bae8f48ce2ffb2da524)

**Review by HassanBahati — APPROVED** [review]
LGTM

**Review by HassanBahati — APPROVED** [review]
LGTM

**Comment by HassanBahati** [comment]
@mosespace thank you for the contribution!

please in the project description add `This pr closes #xx` where xx is the issue number of the issues that this pr resolves.

This will close those issues automatically when this pr is merged

**Comment by mosespace** [comment]
> @mosespace thank you for the contribution!
> 
> please in the description of this pr add `This pr closes #xx` where xx is the issue number of the issues that this pr resolves.
> 
> This will close those issues automatically when this pr is merged

Thank you for the appreciation.
Am looking forward to resolving other issue

**Comment by HassanBahati** [comment]
> > @mosespace thank you for the contribution!
> > please in the description of this pr add `This pr closes #xx` where xx is the issue number of the issues that this pr resolves.
> > This will close those issues automatically when this pr is merged
> 
> Thank you for the appreciation. Am looking forward to resolving other issue

yah sure, let me add more issues shortly....

> @mosespace thank you for the contribution!
> 
> please in the description of this pr add `This pr closes #xx` where xx is the issue number of the issues that this pr resolves.
> 
> This will close those issues automatically when this pr is merged

@mosespace i think for the second issue you have tagged i think you meant #105 rather than #103

**Comment by HassanBahati** [comment]
@ht-thomas this is ready for merging

**Comment by mosespace** [comment]
> > > @mosespace thank you for the contribution!
> > > please in the description of this pr add `This pr closes #xx` where xx is the issue number of the issues that this pr resolves.
> > > This will close those issues automatically when this pr is merged
> > 
> > 
> > Thank you for the appreciation. Am looking forward to resolving other issue
> 
> yah sure, let me add more issues shortly....
> 
> > @mosespace thank you for the contribution!
> > please in the description of this pr add `This pr closes #xx` where xx is the issue number of the issues that this pr resolves.
> > This will close those issues automatically when this pr is merged
> 
> @mosespace i think for the second issue you have tagged i think you meant #105 rather than #103

@HassanBahati thank you, i have resolved it

**Comment by mosespace** [comment]
> @ht-thomas this is ready for merging

@ht-thomas let's move on

**Pull request merged**
