### PR TITLE
Docs: render animation  object documentation

### PR DESCRIPTION
**Pull request by HassanBahati**
* **Please check if the PR fulfills these requirements**
- [x] Docs have been added / updated (for bug fixes / features)
- [x] I have included in this PR's description the statement `closes #xx` or `fixes #xx` where #xx is the number of the issue being addressed.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
1. Adds nav item for objects
2. renders animation object params

* **What is the current behavior?** (You can also link to an open issue here)
None

* **What is the new behavior (if this is a feature change)?**
Screenshot from 2022-11-24 10-46-22

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
None

* **Other information**:

### CODE REVIEW

**Comment by HassanBahati** [comment]
@ht-thomas @kallyas theses Parameter do not appear in the function signature;
- `thumb`
- `file_name`
- `mime_type`
- `file_size`
Screenshot from 2022-11-24 11-01-50

would they have any implication?

**Comment by kallyas** [comment]
@HassanBahati let me look through

**Comment by kallyas** [comment]
> 

They are optional, that's why

**Comment by ht-thomas** [comment]
like @kallyas said, they are optional as seen on the telegram bot api page. We decided to have only arguments considered as compulsory added to the function signature. I'm trying to find the issue where this was resolved but I can't find it, but it was resolved somewhere

**Comment by HassanBahati** [comment]
alright @ht-thomas , the linting in my ide was flagging them thats why i had asked.

Yes it is ready for merging

**Pull request merged**
